// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: proto/policyproxy/v1/policy_service.proto

package policyproxyv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PolicyProxyService_ListPoliciesStatus_FullMethodName = "/policyproxy.v1.PolicyProxyService/ListPoliciesStatus"
)

// PolicyProxyServiceClient is the client API for PolicyProxyService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PolicyProxyServiceClient interface {
	// ListPoliciesStatus returns the status of tracing policies known to Tetragon.
	ListPoliciesStatus(ctx context.Context, in *ListPoliciesStatusRequest, opts ...grpc.CallOption) (*ListPoliciesStatusResponse, error)
}

type policyProxyServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPolicyProxyServiceClient(cc grpc.ClientConnInterface) PolicyProxyServiceClient {
	return &policyProxyServiceClient{cc}
}

func (c *policyProxyServiceClient) ListPoliciesStatus(ctx context.Context, in *ListPoliciesStatusRequest, opts ...grpc.CallOption) (*ListPoliciesStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListPoliciesStatusResponse)
	err := c.cc.Invoke(ctx, PolicyProxyService_ListPoliciesStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PolicyProxyServiceServer is the server API for PolicyProxyService service.
// All implementations must embed UnimplementedPolicyProxyServiceServer
// for forward compatibility.
type PolicyProxyServiceServer interface {
	// ListPoliciesStatus returns the status of tracing policies known to Tetragon.
	ListPoliciesStatus(context.Context, *ListPoliciesStatusRequest) (*ListPoliciesStatusResponse, error)
	mustEmbedUnimplementedPolicyProxyServiceServer()
}

// UnimplementedPolicyProxyServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPolicyProxyServiceServer struct{}

func (UnimplementedPolicyProxyServiceServer) ListPoliciesStatus(context.Context, *ListPoliciesStatusRequest) (*ListPoliciesStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListPoliciesStatus not implemented")
}
func (UnimplementedPolicyProxyServiceServer) mustEmbedUnimplementedPolicyProxyServiceServer() {}
func (UnimplementedPolicyProxyServiceServer) testEmbeddedByValue()                            {}

// UnsafePolicyProxyServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PolicyProxyServiceServer will
// result in compilation errors.
type UnsafePolicyProxyServiceServer interface {
	mustEmbedUnimplementedPolicyProxyServiceServer()
}

func RegisterPolicyProxyServiceServer(s grpc.ServiceRegistrar, srv PolicyProxyServiceServer) {
	// If the following call pancis, it indicates UnimplementedPolicyProxyServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PolicyProxyService_ServiceDesc, srv)
}

func _PolicyProxyService_ListPoliciesStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPoliciesStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PolicyProxyServiceServer).ListPoliciesStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PolicyProxyService_ListPoliciesStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PolicyProxyServiceServer).ListPoliciesStatus(ctx, req.(*ListPoliciesStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PolicyProxyService_ServiceDesc is the grpc.ServiceDesc for PolicyProxyService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PolicyProxyService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "policyproxy.v1.PolicyProxyService",
	HandlerType: (*PolicyProxyServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListPoliciesStatus",
			Handler:    _PolicyProxyService_ListPoliciesStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/policyproxy/v1/policy_service.proto",
}
