// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: proto/policyproxy/v1/policy_service.proto

package policyproxyv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TracingPolicyState int32

const (
	// unknown state
	TracingPolicyState_TP_STATE_UNKNOWN TracingPolicyState = 0
	// loaded and enabled
	TracingPolicyState_TP_STATE_ENABLED TracingPolicyState = 1
	// loaded but disabled
	TracingPolicyState_TP_STATE_DISABLED TracingPolicyState = 2
	// failed to load
	TracingPolicyState_TP_STATE_LOAD_ERROR TracingPolicyState = 3
	// failed during lifetime
	TracingPolicyState_TP_STATE_ERROR TracingPolicyState = 4
	// in the process of loading
	TracingPolicyState_TP_STATE_LOADING TracingPolicyState = 5
	// in the process of unloading
	TracingPolicyState_TP_STATE_UNLOADING TracingPolicyState = 6
)

// Enum value maps for TracingPolicyState.
var (
	TracingPolicyState_name = map[int32]string{
		0: "TP_STATE_UNKNOWN",
		1: "TP_STATE_ENABLED",
		2: "TP_STATE_DISABLED",
		3: "TP_STATE_LOAD_ERROR",
		4: "TP_STATE_ERROR",
		5: "TP_STATE_LOADING",
		6: "TP_STATE_UNLOADING",
	}
	TracingPolicyState_value = map[string]int32{
		"TP_STATE_UNKNOWN":    0,
		"TP_STATE_ENABLED":    1,
		"TP_STATE_DISABLED":   2,
		"TP_STATE_LOAD_ERROR": 3,
		"TP_STATE_ERROR":      4,
		"TP_STATE_LOADING":    5,
		"TP_STATE_UNLOADING":  6,
	}
)

func (x TracingPolicyState) Enum() *TracingPolicyState {
	p := new(TracingPolicyState)
	*p = x
	return p
}

func (x TracingPolicyState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TracingPolicyState) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_policyproxy_v1_policy_service_proto_enumTypes[0].Descriptor()
}

func (TracingPolicyState) Type() protoreflect.EnumType {
	return &file_proto_policyproxy_v1_policy_service_proto_enumTypes[0]
}

func (x TracingPolicyState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TracingPolicyState.Descriptor instead.
func (TracingPolicyState) EnumDescriptor() ([]byte, []int) {
	return file_proto_policyproxy_v1_policy_service_proto_rawDescGZIP(), []int{0}
}

type ListPoliciesStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPoliciesStatusRequest) Reset() {
	*x = ListPoliciesStatusRequest{}
	mi := &file_proto_policyproxy_v1_policy_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPoliciesStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPoliciesStatusRequest) ProtoMessage() {}

func (x *ListPoliciesStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_policyproxy_v1_policy_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPoliciesStatusRequest.ProtoReflect.Descriptor instead.
func (*ListPoliciesStatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_policyproxy_v1_policy_service_proto_rawDescGZIP(), []int{0}
}

type PolicyStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         TracingPolicyState     `protobuf:"varint,1,opt,name=state,proto3,enum=policyproxy.v1.TracingPolicyState" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PolicyStatus) Reset() {
	*x = PolicyStatus{}
	mi := &file_proto_policyproxy_v1_policy_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PolicyStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PolicyStatus) ProtoMessage() {}

func (x *PolicyStatus) ProtoReflect() protoreflect.Message {
	mi := &file_proto_policyproxy_v1_policy_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PolicyStatus.ProtoReflect.Descriptor instead.
func (*PolicyStatus) Descriptor() ([]byte, []int) {
	return file_proto_policyproxy_v1_policy_service_proto_rawDescGZIP(), []int{1}
}

func (x *PolicyStatus) GetState() TracingPolicyState {
	if x != nil {
		return x.State
	}
	return TracingPolicyState_TP_STATE_UNKNOWN
}

type ListPoliciesStatusResponse struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Policies      map[string]*PolicyStatus `protobuf:"bytes,1,rep,name=policies,proto3" json:"policies,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPoliciesStatusResponse) Reset() {
	*x = ListPoliciesStatusResponse{}
	mi := &file_proto_policyproxy_v1_policy_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPoliciesStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPoliciesStatusResponse) ProtoMessage() {}

func (x *ListPoliciesStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_policyproxy_v1_policy_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPoliciesStatusResponse.ProtoReflect.Descriptor instead.
func (*ListPoliciesStatusResponse) Descriptor() ([]byte, []int) {
	return file_proto_policyproxy_v1_policy_service_proto_rawDescGZIP(), []int{2}
}

func (x *ListPoliciesStatusResponse) GetPolicies() map[string]*PolicyStatus {
	if x != nil {
		return x.Policies
	}
	return nil
}

var File_proto_policyproxy_v1_policy_service_proto protoreflect.FileDescriptor

const file_proto_policyproxy_v1_policy_service_proto_rawDesc = "" +
	"\n" +
	")proto/policyproxy/v1/policy_service.proto\x12\x0epolicyproxy.v1\"\x1b\n" +
	"\x19ListPoliciesStatusRequest\"H\n" +
	"\fPolicyStatus\x128\n" +
	"\x05state\x18\x01 \x01(\x0e2\".policyproxy.v1.TracingPolicyStateR\x05state\"\xcd\x01\n" +
	"\x1aListPoliciesStatusResponse\x12T\n" +
	"\bpolicies\x18\x01 \x03(\v28.policyproxy.v1.ListPoliciesStatusResponse.PoliciesEntryR\bpolicies\x1aY\n" +
	"\rPoliciesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x122\n" +
	"\x05value\x18\x02 \x01(\v2\x1c.policyproxy.v1.PolicyStatusR\x05value:\x028\x01*\xb2\x01\n" +
	"\x12TracingPolicyState\x12\x14\n" +
	"\x10TP_STATE_UNKNOWN\x10\x00\x12\x14\n" +
	"\x10TP_STATE_ENABLED\x10\x01\x12\x15\n" +
	"\x11TP_STATE_DISABLED\x10\x02\x12\x17\n" +
	"\x13TP_STATE_LOAD_ERROR\x10\x03\x12\x12\n" +
	"\x0eTP_STATE_ERROR\x10\x04\x12\x14\n" +
	"\x10TP_STATE_LOADING\x10\x05\x12\x16\n" +
	"\x12TP_STATE_UNLOADING\x10\x062\x83\x01\n" +
	"\x12PolicyProxyService\x12m\n" +
	"\x12ListPoliciesStatus\x12).policyproxy.v1.ListPoliciesStatusRequest\x1a*.policyproxy.v1.ListPoliciesStatusResponse\"\x00BJZHgithub.com/neuvector/runtime-enforcer/proto/policyproxy/v1;policyproxyv1b\x06proto3"

var (
	file_proto_policyproxy_v1_policy_service_proto_rawDescOnce sync.Once
	file_proto_policyproxy_v1_policy_service_proto_rawDescData []byte
)

func file_proto_policyproxy_v1_policy_service_proto_rawDescGZIP() []byte {
	file_proto_policyproxy_v1_policy_service_proto_rawDescOnce.Do(func() {
		file_proto_policyproxy_v1_policy_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_policyproxy_v1_policy_service_proto_rawDesc), len(file_proto_policyproxy_v1_policy_service_proto_rawDesc)))
	})
	return file_proto_policyproxy_v1_policy_service_proto_rawDescData
}

var file_proto_policyproxy_v1_policy_service_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_policyproxy_v1_policy_service_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_policyproxy_v1_policy_service_proto_goTypes = []any{
	(TracingPolicyState)(0),            // 0: policyproxy.v1.TracingPolicyState
	(*ListPoliciesStatusRequest)(nil),  // 1: policyproxy.v1.ListPoliciesStatusRequest
	(*PolicyStatus)(nil),               // 2: policyproxy.v1.PolicyStatus
	(*ListPoliciesStatusResponse)(nil), // 3: policyproxy.v1.ListPoliciesStatusResponse
	nil,                                // 4: policyproxy.v1.ListPoliciesStatusResponse.PoliciesEntry
}
var file_proto_policyproxy_v1_policy_service_proto_depIdxs = []int32{
	0, // 0: policyproxy.v1.PolicyStatus.state:type_name -> policyproxy.v1.TracingPolicyState
	4, // 1: policyproxy.v1.ListPoliciesStatusResponse.policies:type_name -> policyproxy.v1.ListPoliciesStatusResponse.PoliciesEntry
	2, // 2: policyproxy.v1.ListPoliciesStatusResponse.PoliciesEntry.value:type_name -> policyproxy.v1.PolicyStatus
	1, // 3: policyproxy.v1.PolicyProxyService.ListPoliciesStatus:input_type -> policyproxy.v1.ListPoliciesStatusRequest
	3, // 4: policyproxy.v1.PolicyProxyService.ListPoliciesStatus:output_type -> policyproxy.v1.ListPoliciesStatusResponse
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_policyproxy_v1_policy_service_proto_init() }
func file_proto_policyproxy_v1_policy_service_proto_init() {
	if File_proto_policyproxy_v1_policy_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_policyproxy_v1_policy_service_proto_rawDesc), len(file_proto_policyproxy_v1_policy_service_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_policyproxy_v1_policy_service_proto_goTypes,
		DependencyIndexes: file_proto_policyproxy_v1_policy_service_proto_depIdxs,
		EnumInfos:         file_proto_policyproxy_v1_policy_service_proto_enumTypes,
		MessageInfos:      file_proto_policyproxy_v1_policy_service_proto_msgTypes,
	}.Build()
	File_proto_policyproxy_v1_policy_service_proto = out.File
	file_proto_policyproxy_v1_policy_service_proto_goTypes = nil
	file_proto_policyproxy_v1_policy_service_proto_depIdxs = nil
}
