package main

import (
	"context"
	"fmt"
	"io"
	"log/slog"
	"os"
	"sort"
	"strings"
	"time"

	"github.com/google/go-cmp/cmp"
	"github.com/rancher-sandbox/runtime-enforcer/internal/grpcexporter"
	agentv1 "github.com/rancher-sandbox/runtime-enforcer/proto/agent/v1"
	"google.golang.org/protobuf/testing/protocmp"
	corev1 "k8s.io/api/core/v1"
	"sigs.k8s.io/controller-runtime/pkg/cache"
)

const staticPodAnnotation = "kubernetes.io/config.mirror"

type nodeName = string

func printNodeAgentCache(w io.Writer,
	nodeName string,
	nodeCache []*agentv1.PodView) {
	fmt.Fprintf(w, "=== Node '%s' cache dump (%d pods) ===\n", nodeName, len(nodeCache))
	for _, view := range nodeCache {
		fmt.Fprintf(
			w,
			"- pod: (%s/%s)-%s\n",
			view.GetMeta().GetNamespace(),
			view.GetMeta().GetName(),
			view.GetMeta().GetId(),
		)
		for containerID, containerMeta := range view.GetContainers() {
			fmt.Fprintf(w, "-- container: (id=%s) %s\n", containerID, containerMeta.GetName())
		}
	}
	fmt.Fprintln(w)
}

func validateAgentCache(w io.Writer,
	agentCachePerNode map[nodeName][]*agentv1.PodView,
	expectedCachePerNode map[nodeName][]*agentv1.PodView) {
	fmt.Fprintf(w, "=== Caches diff with cluster state: %v ===\n", time.Now())
	hasDiff := false

	if len(expectedCachePerNode) != len(agentCachePerNode) {
		// This is possible for example when the runtime enforcer is not installed on some agents.
		fmt.Fprintf(
			w,
			"- Some nodes in the cluster don't have an agent cache. Nodes in the cluster: %d, agent caches: %d.\n",
			len(expectedCachePerNode),
			len(agentCachePerNode),
		)
	}

	// We are sure the number of nodes is the same
	for nodeName, expectedPods := range expectedCachePerNode {
		// Skip nodes without an agent cache
		actualPods, ok := agentCachePerNode[nodeName]
		if !ok {
			fmt.Fprintf(w, "- node '%s': no agent cache available\n", nodeName)
			continue
		}

		// Order the slices by pod Name.
		sort.Slice(expectedPods, func(i, j int) bool {
			return expectedPods[i].GetMeta().GetName() < expectedPods[j].GetMeta().GetName()
		})
		sort.Slice(actualPods, func(i, j int) bool {
			return actualPods[i].GetMeta().GetName() < actualPods[j].GetMeta().GetName()
		})

		if diff := cmp.Diff(expectedPods, actualPods, protocmp.Transform()); diff != "" {
			fmt.Fprintf(w, "- cache on node '%s' is not aligned\n%s\n",
				nodeName, diff)
			hasDiff = true
			// In case of diff, print the agent cache
			printNodeAgentCache(w, nodeName, agentCachePerNode[nodeName])
		}
	}

	if !hasDiff {
		fmt.Fprintln(w, "caches are aligned")
	} else {
		fmt.Fprintln(w, "caches are not aligned")
	}
}

func containerIDFromContainerStatus(c *corev1.ContainerStatus) string {
	// This is the layout of a container inside the pod
	// "containerd://d4813c4da49cbaa50542f86bd077608e5d3da101efef52642346803c4d5a902b"
	// we want to remove the prefix
	ret := c.ContainerID
	if idx := strings.Index(ret, "://"); idx != -1 {
		ret = ret[idx+3:]
	}
	return ret
}

func addContainerToPodView(containerStatus *corev1.ContainerStatus, podView *agentv1.PodView) {
	containerID := containerIDFromContainerStatus(containerStatus)
	containerMeta := &agentv1.ContainerMeta{
		Id:       containerID,
		Name:     containerStatus.Name,
		CgroupId: 0, // we don't recover it today
	}
	podView.Containers[containerID] = containerMeta
}

func podToView(pod *corev1.Pod) *agentv1.PodView {
	// If this is a static Pod we replace the Pod UID generated by the API server
	// with the one from the annotation.
	podUID := string(pod.UID)
	if pod.Annotations != nil && pod.Annotations[staticPodAnnotation] != "" {
		podUID = pod.Annotations[staticPodAnnotation]
	}

	podView := &agentv1.PodView{
		Meta: &agentv1.PodMeta{
			Id:        podUID,
			Name:      pod.Name,
			Namespace: pod.Namespace,
			// We don't set the labels because they will be different from the ones the NRI find.
			// Labels:    pod.Labels,
		},
		Containers: make(map[string]*agentv1.ContainerMeta),
	}

	for _, containerStatus := range pod.Status.InitContainerStatuses {
		addContainerToPodView(&containerStatus, podView)
	}
	for _, containerStatus := range pod.Status.ContainerStatuses {
		addContainerToPodView(&containerStatus, podView)
	}
	for _, containerStatus := range pod.Status.EphemeralContainerStatuses {
		addContainerToPodView(&containerStatus, podView)
	}
	return podView
}

func zeroOutUnrecoverableDetails(cache map[nodeName][]*agentv1.PodView) {
	for _, podViews := range cache {
		for _, podView := range podViews {
			// At the moment we don't recover them from the ownerReference when we get the pod from the informer.
			podView.Meta.WorkloadName = ""
			podView.Meta.WorkloadType = ""

			// Zero out labels since we don't get the full set from the NRI.
			// Labels we have in our view won't match the ones in the cluster.
			podView.Meta.Labels = nil

			// Zero out cgroup ID, at the moment we don't recover it when we get the pod from the informer.
			for _, containerMeta := range podView.GetContainers() {
				containerMeta.CgroupId = 0
			}
		}
	}
}

func validatePodCacheIntegrity(ctx context.Context,
	logger *slog.Logger,
	c cache.Cache,
	pool *grpcexporter.AgentClientPool,
) error {
	clients, err := pool.UpdatePool(ctx, c)
	if err != nil {
		return fmt.Errorf("failed to update agent client pool: %w", err)
	}

	// Build the agent cache per node from GRPC.
	agentCachePerNode := make(map[nodeName][]*agentv1.PodView)
	for nodeName, client := range clients {
		if client == nil {
			logger.ErrorContext(ctx, "Agent client is nil", "node", nodeName)
			continue
		}

		var podCacheList []*agentv1.PodView
		podCacheList, err = client.ListPodCache(ctx)
		if err != nil {
			pool.MarkStaleAgentClient(nodeName)
			logger.ErrorContext(ctx, "Failed to list pod cache", "node", nodeName, "error", err)
			continue
		}
		agentCachePerNode[nodeName] = podCacheList
	}

	// Build the expected cache from the cluster pod list.
	expectedCachePerNode := make(map[nodeName][]*agentv1.PodView)
	var podList corev1.PodList
	if err = c.List(ctx, &podList); err != nil {
		return fmt.Errorf("failed to list pods in the cluster: %w", err)
	}
	for i := range podList.Items {
		pod := &podList.Items[i]
		expectedCachePerNode[pod.Spec.NodeName] = append(
			expectedCachePerNode[pod.Spec.NodeName],
			podToView(pod),
		)
	}

	// Scraping pods from the cluster we don't get some details we get during NRI extraction and vice versa.
	// So we need to zero out those details in the agent cache before doing the comparison.
	zeroOutUnrecoverableDetails(agentCachePerNode)

	// Print diff between expected and actual cache per node.
	validateAgentCache(os.Stdout, agentCachePerNode, expectedCachePerNode)
	return nil
}
